[project]
name = "mcp-teste"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.14.4",
    "requests>=2.32.5",
    "wikipedia>=1.4.0",
]
